### ISSUE TITLE
which version support rpm <=4.12.0-1

### ISSUE THREAD

**Issue by leejaygo** [electron-userland/electron-installer-redhat#157]
I use electron-installer-redhat to build rpm package，but when the computer just support rpm <=4.12，update rpm is not supported, so which version can support rpm <=4.12?

**Comment by fcastilloec** [comment]
We don't support version that old of rpm, you should try using Docker or anything else you can with a newer version of rpm.
You can try installing any old version of our package until one works for you but it's not advisable.  There have been multiple bugs and vulnerability fixes since then, and older versions of our package will only work with older versions of electron.

**Comment by AdrianDC** [comment]
As a manual and self maintained dependency list alternative, this can be used for CentOS 7 targets (using RPM 4.11.3 releases) : 

```
sed -i "s#throw new Error('Please upgrade to RPM 4.13.*#console.warn('You are using RPM < 4.13')\n      return { requires: [ 'gtk3', 'libnotify', 'nss', 'libXScrnSaver', 'libXtst', 'xdg-utils', 'at-spi2-core', 'libdrm', 'mesa-libgbm', 'libxcb' ] }#g" ./node_modules/electron-installer-redhat/src/dependencies.js
```

Subsequent builds will no longer use the original boolean dependencies from RPM 4.13 (hence target locked),
which in specific single-target deliveries does behave like older versions while retaining recent upgrades.
