### ISSUE TITLE
Shared symlink fails if package "name" includes organisation name

### ISSUE THREAD

**Issue by riggerthegeek** [electron-userland/electron-installer-redhat#81]
**What version of `electron-installer-redhat` are you using?**
0.5.0

**What version of `node` and `npm` are you using?**
6.12.2/3.10.10

**What operating system are you using?**
Fedora 27

**Can you compile the [example app](https://github.com/unindented/electron-installer-redhat/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**
Built the electron example app with an organisation name in the package.json - `@org/poopie". Failed to build with error:
```
Creating package (this may take a while)
Error: Error creating binary file: ENOENT: no such file or directory, symlink '../share/@org/poopie/@org/poopie' -> '/tmp/electron-11806-7442-bt143i.ev7ibv5cdi/@org/BUILD/usr/bin/@org/poopie'
    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/electron-installer-redhat/src/installer.js:201:21
    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:473:16
    at next (/home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:5315:29)
    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:958:16
    at FSReqWrap.oncomplete (fs.js:123:15) 'Error: Error creating binary file: ENOENT: no such file or directory, symlink \'../share/@org/poopie/@org/poopie\' -> \'/tmp/electron-11806-7442-bt143i.ev7ibv5cdi/@org/BUILD/usr/bin/@org/poopie\'\n    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/electron-installer-redhat/src/installer.js:201:21\n    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:473:16\n    at next (/home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:5315:29)\n    at /home/username/Desktop/electron-installer-redhat-master/example/node_modules/async/dist/async.js:958:16\n    at FSReqWrap.oncomplete (fs.js:123:15)'
```

**What did you expect to happen?**
To build successfully

**What actually happened?**
Failed to build

**Comment by fcastilloec** [comment]
I'm not sure what you mean by the "organization name". Can you paste the content of your `package.json` here, or if it's too long, a link to gits or similar?

**Comment by riggerthegeek** [comment]
By organisation name, I mean the npm organisation - ie, the `name` in the package.json in the in format `@org/name`. I was using `@nodedb/core`

I think the reason for this is because the `node_modules` puts that in a subdirectory, eg "/node_modules/@nodedb/core" rather than '/node_modules/core'. It seems a relatively easy fix and can get a PR done for it in the next couple of weeks (currently on holiday)

**Comment by fcastilloec** [comment]
So, originally I thought you were referring to dependencies that were part of a scope/organization. This shouldn't be any problem for this module. Thanks to your clarification, the problem is with the name of the module you're trying to package. The issue is that the name contains the `/` and `@` characters. So, when creating a package name `@nodedb/core`, it's creating a directory named `@nodedb` and a package named `core` inside becasue of `/`; and when trying to look for a file named `@nodedb/core` it will absolutely fail.
On top of that, `rpmbuld` will fail if we use any character outside of [this list](https://fedoraproject.org/wiki/Packaging:Naming?rd=Packaging:NamingGuidelines#Common_Character_Set_for_Package_Naming

I recommend that you use [`options.name`](https://github.com/electron-userland/electron-installer-redhat#optionsname) so you can rename your package to an appropiate name. And perhaps use [`rename`](https://github.com/electron-userland/electron-installer-redhat#rename) to change the final package name to whatever you want

I think that we can replace any `/` character in the name for `_` and delete `@` if it's the first character in the name.
