### ISSUE TITLE
More specific dependencies

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-installer-redhat#89]
I noticed today that the dependency list is really short, compared to [the amount of logic needed for `electron-installer-debian`](https://github.com/electron-userland/electron-installer-debian/blob/v1.0.0/src/dependencies.js). Not knowing much about the RedHat side of Linux, is this normal? Should it look more like `electron-installer-debian`?

CC: @fcastilloec

**Comment by fcastilloec** [comment]
@malept is this the new list of dependencies for electron? https://github.com/electron/electron/blob/master/build/install-build-deps.sh#L189

Last time we checked dependencies for `-debian` module,  I think electron was at `v2`. Has anything changed in `v3` or `v4` that we should consider?

**Comment by fcastilloec** [comment]
I'm going to list the fedora equivalent packages here until we create a PR that handles dependencies in the same way `-debian` does. Here's a list of all packages used for all versions of electron from `-debian`

Debian | RedHat
--- |	---
libnotify4|	libnotify
libnss3 |	nss
libxss1 |	libXScrnSaver
libxtst6 |	libXtst
xdg-utils |	xdg-utils
libgtk-3-0 |	gtk3
libgtk2.0-0 |	gtk2
libgconf2-4 |	GConf2
libuuid1 |	libuuid
gvfs-bin |	gvfs-client
kde-cli-tools |	kde-cli-tools
kde-runtime |	kde-runtime
trash-cli |	trash-cli
libglib2.0-bin |	glib2

It's funny that originally, the only package that I knew was required in RedHat/Fedora, was `libXScrnSaver` and it turns out that it was the package that we forgot to add in `-debian`

**Comment by malept** [comment]
It occurred to me that we need to fix `options.requires` so that it doesn't override the Electron dependencies, much like what happens in `-debian`.
